# Generated by Django 5.1.2 on 2024-11-01 22:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subreddit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("types", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "last_checked",
                    models.DateField(default=datetime.datetime(2020, 1, 1, 0, 0)),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=300)),
                ("content", models.CharField(blank=True, max_length=2000, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("video", models.FileField(blank=True, null=True, upload_to="videos/")),
                ("posted_at", models.DateTimeField()),
                ("author", models.CharField(max_length=50)),
                (
                    "subreddit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posts.subreddit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContentGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "subreddits",
                    models.ManyToManyField(
                        related_name="content_groups", to="posts.subreddit"
                    ),
                ),
            ],
        ),
    ]
