# Generated by Django 5.1.2 on 2025-01-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentgroup",
            name="theme",
            field=models.CharField(blank=True, default="", max_length=250, null=True),
        ),
    ]
