# Generated by Django 5.1.2 on 2025-01-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_remove_contentgroup_theme_contentgroup_end_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentgroup",
            name="end_text",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="contentgroup",
            name="start_text",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
