# Generated by Django 5.1.2 on 2025-01-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_contentgroup_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentgroup",
            name="background",
            field=models.CharField(
                choices=[
                    ("black", "Black"),
                    ("minecraft", "Minecraft"),
                    ("subway", "Subway"),
                    ("not-black", "Notblack"),
                ],
                default="minecraft",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="contentgroup",
            name="media_per_screen",
            field=models.IntegerField(choices=[(1, "one"), (2, "two")], default=1),
        ),
    ]
