# Generated by Django 5.1.5 on 2025-01-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_contentgroup_background_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentgroup",
            name="end_text",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="contentgroup",
            name="start_text",
            field=models.CharField(default="", max_length=50),
        ),
    ]
