# Generated by Django 5.1.5 on 2025-01-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_alter_contentgroup_end_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentgroup",
            name="upload_description",
            field=models.CharField(
                default="#funny #meme #memes #comedy #lol", max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
