# Generated by Django 5.1.2 on 2025-01-22 15:21

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedvideo",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to=videos.models.randomize_name
            ),
        ),
    ]
