# Generated by Django 5.1.2 on 2025-01-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0003_generatedvideo_used_media"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generatedvideo",
            name="length",
        ),
        migrations.AddField(
            model_name="generatedvideo",
            name="meta_data",
            field=models.JSONField(default={}, verbose_name="metadata"),
        ),
    ]
