# Generated by Django 5.1.2 on 2024-11-14 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="generated_videos/"
                    ),
                ),
                ("length", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                (
                    "content_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="posts.contentgroup",
                    ),
                ),
            ],
        ),
    ]
