# Generated by Django 5.1.2 on 2025-01-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_contentgroup_background_and_more"),
        ("videos", "0002_alter_generatedvideo_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedvideo",
            name="used_media",
            field=models.ManyToManyField(
                related_name="generated_videos", to="posts.post"
            ),
        ),
    ]
