# Generated by Django 5.1.2 on 2025-01-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0004_remove_generatedvideo_length_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedvideo",
            name="meta_data",
            field=models.JSONField(default=dict, verbose_name="metadata"),
        ),
    ]
