# Generated by Django 5.1.5 on 2025-01-26 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0005_alter_generatedvideo_meta_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Youtube", "shorts"),
                            ("Instagram", "reels"),
                            ("TikTok", "tiktok"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "uploaded_video_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "video",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="videos.generatedvideo",
                    ),
                ),
            ],
        ),
    ]
