# Generated by Django 5.1.2 on 2025-01-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_contentgroup_theme"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentgroup",
            name="theme",
        ),
        migrations.AddField(
            model_name="contentgroup",
            name="end_text",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="contentgroup",
            name="start_text",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
