# Generated by Django 5.1.2 on 2025-01-22 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_contentgroup_end_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentgroup",
            name="media_per_video",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(500),
                ],
            ),
        ),
    ]
