# Generated by Django 5.1.2 on 2025-01-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_contentgroup_media_per_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentgroup",
            name="type",
            field=models.CharField(
                choices=[("img", "Image"), ("vid", "Video"), ("text", "Text")],
                default="img",
                max_length=4,
            ),
        ),
    ]
