# Generated by Django 5.1.5 on 2025-02-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0009_contentgroup_upload_description_alter_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentgroup",
            name="song_title",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="contentgroup",
            name="song_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
