# Generated by Django 5.1.5 on 2025-02-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_contentgroup_song_title_contentgroup_song_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentgroup",
            name="background",
            field=models.CharField(
                choices=[
                    ("black", "Black"),
                    ("minecraft", "Minecraft"),
                    ("subway", "Subway"),
                    ("chill", "Chill"),
                    ("not-black", "Notblack"),
                ],
                default="minecraft",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="contentgroup",
            name="song_title",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="contentgroup",
            name="song_type",
            field=models.CharField(
                blank=True, default="upbeat-popular", max_length=20, null=True
            ),
        ),
    ]
